DUMMY_COLS = [
    ("key", None),
    ("revision", None),
    ("actualduration", None),
    ("canceldate", None),
    ("rejectdate", None),
    ("rejectionreason", None),
    ("jobstart_tmp", None),
    ("latitude", None),
    ("longitude", None),
    ("mrooperationno", None),
    ("mroorderid", None),
    ("mroordershorttext", None),
    ("incompletereason_displaystring", None),
    ("incompletereason", None),
    ("fsmopsaddonworkkey", None),
    ("mromaintenanceactivitytype", None),
    ("mrosupfuncloc", None),
    ("mromaintenanceactivitytype", None),
    ("mrocancelreasons", None),
    ("excludedengineers", None),
    ("tasktype_key", None),
    ("duedatediff", None),
    ("ondevicedate", None),
    ("mroassetlocation_key", None),
    ("netoperatingincome", None),
    ("sourcesystem", "Dummy"),
    ("jobcategory", "Dummy"),
    ("mrocompletionnotes", "Dummy"),
    ("mrodescription", "Dummy"),
    ("jobstatus", "Completed"),
    ("jobtype", "N/A"),
    ("mroassetlocation", "WELLHEAD"),
    ("mrolocationtype", "WELL"),
    ("ismegatask", False),
    ("wassuspended", False),
    ("assetid", "USEF-255-33666"),
    ("mroassetfind", "USEF-255-PAD-2048"),
    ("ismdt_so", False),
    ("ismst_so", False),
    ("rtisrecurringtask", False),
    ("extensionflag", False),
    ("mrospecialwellsproject", "False"),
    ("shutinwell", "False"),
    ("fsmschedulepriority", "MED-HIGH"),
    ("fsmopsaddonwork", "[]"),
    ("number", 1),
    ("plannedduration", 0),
    ("dynamicpriority", 0),
    ("extensioncount", 0),
    ("maxextension", 0),
    ("extendduration", 0),
    ("mroparentmocid", None),
    ("fsmglobalforms", None),
    ("reliabilityvaporrecoveryunits", None),
    ("reliabilitypipelinepumps", None),
    ("mrotestwellinspection", None),
    ("fsmefaircompressor", None),
    ("baknotltsi", None),
    ("bakstuffingboxleaking", None),
    ("ecpnotrequired", None),
    ("fsmefdataeditpdm_displaystring", None),
    ("fsmefdataeditpdm_key", None),
    ("fsmeffireextinguisher", None),
    ("fsmefhesinspections", None),
    ("fsmefnormsurvey", None),
    ("fsmefsitecheck_displaystring", None),
    ("fsmefsitecheck_key", None),
    ("fsmorbmaintforms", None),
    ("fsmorbopsformsreq", None),
    ("mropilotlitatarrival", None),
    ("mropilotlitatdeparture", None),
    ("onholdnotes", None),
    ("rbbelastcompleted", None),
    ("rejectionnotes", None),
    ("tasktype_string", None),
    ("mrostdtextkey", None),
    ("mrounitofmeasure", None),
    ("hashighpriorityalert", None),
]


TASK_LAST_REVISION_COLS = [
    ("key", "key"),
    ("revision", "revision"),
    ("stamp_timecreated", "timecreated"),
    ("stamp_timecreated_lcltz", "timecreated_lcltz"),
    ("stamp_createdby", "sourcesystem"),
    ("callid", "callid"),
    ("number", "number"),
    ("region_displaystring", "jobregion"),
    ("district_displaystring", "jobdistrict"),
    ("tasktypecategory_displaystring", "jobcategory"),
    ("tasktype_displaystring", "jobtype"),
    ("earlystart", "earlystart"),
    ("duedate", "duedate"),
    ("stamp_timemodified", "timemodified"),
    ("duration", "plannedduration"),
    ("assignmentstart", "assignmentstart"),
    ("assignmentfinish", "assignmentfinish"),
    ("assignedengineer_key", "assignedreskey"),
    ("assignedengineer_displaystring", "assignedresource"),
    ("status_displaystring", "jobstatus"),
    ("dynamicpriority", "dynamicpriority"),
    ("workingarea_displaystring", "workingarea"),
    ("scheduledate", "scheduleddate"),
    ("dispatchdate", "dispatchdate"),
    ("confirmationdate", "acknowledgeddate"),
    ("traveldate", "traveldate"),
    ("onsitedate", "onsitedate"),
    ("completiondate", "completedate"),
    ("cancellationdate", "canceldate"),
    ("rejecteddate", "rejectdate"),
    ("rejectionreason_displaystring", "rejectionreason"),
    ("mroassetlocation_displaystring", "mroassetlocation"),
    ("fsmschedulepriority_displaystring", "fsmschedulepriority"),
    ("mrocancelreasons_displaystring", "mrocancelreasons"),
    ("latitude", "latitude"),
    ("longitude", "longitude"),
    ("mrooperationno", "mrooperationno"),
    ("mroorderid", "mroorderid"),
    ("mroordershorttext", "mroordershorttext"),
    ("mroassetlocation_key", "mroassetlocation_key"),
    ("ismegatask", "ismegatask"),
    ("wassuspended", "wassuspended"),
    ("ismdt_so", "ismdt_so"),
    ("ismst_so", "ismst_so"),
    ("rtisrecurringtask", "rtisrecurringtask"),
    ("mrocompletionnotes", "mrocompletionnotes"),
    ("fsmopsaddonwork", "fsmopsaddonwork"),
    ("mrodescription", "mrodescription"),
    ("incompletereason_displaystring", "incompletereason_displaystring"),
    ("extensioncount", "extensioncount"),
    ("maxextension", "maxextension"),
    ("extendduration", "extendduration"),
    ("extensionflag", "extensionflag"),
    ("mromaintenanceactivitytype", "mromaintenanceactivitytype"),
    ("excludedengineers", "excludedengineers"),
    ("tasktype_key", "tasktype_key"),
    ("ondevicedate", "ondevicedate"),
    ("netoperatingincome", "netoperatingincome"),
    ("mroparentmocid", "mroparentmocid"),
    ("fsmglobalforms_key", "fsmglobalforms"),
    ("reliabilityvaporrecoveryunits_key", "reliabilityvaporrecoveryunits"),
    ("reliabilitypipelinepumps_key", "reliabilitypipelinepumps"),
    ("mrotestwellinspection_key", "mrotestwellinspection"),
    ("fsmefaircompressor_key", "fsmefaircompressor"),
    ("baknotltsi", "baknotltsi"),
    ("bakstuffingboxleaking", "bakstuffingboxleaking"),
    ("ecpnotrequired", "ecpnotrequired"),
    ("fsmefdataeditpdm_displaystring", "fsmefdataeditpdm_displaystring"),
    ("fsmefdataeditpdm_key", "fsmefdataeditpdm_key"),
    ("fsmeffireextinguisher_key", "fsmeffireextinguisher"),
    ("fsmefhesinspections_key", "fsmefhesinspections"),
    ("fsmefnormsurvey_key", "fsmefnormsurvey"),
    ("fsmefsitecheck_displaystring", "fsmefsitecheck_displaystring"),
    ("fsmefsitecheck_key", "fsmefsitecheck_key"),
    ("fsmorbmaintforms_key", "fsmorbmaintforms"),
    ("fsmorbopsformsreq_key", "fsmorbopsformsreq"),
    ("mropilotlitatarrival_key", "mropilotlitatarrival"),
    ("mropilotlitatdeparture_key", "mropilotlitatdeparture"),
    ("onholdnotes", "onholdnotes"),
    ("rbbelastcompleted", "rbbelastcompleted"),
    ("rejectionnotes", "rejectionnotes"),
    ("tasktype_string", "tasktype_string"),
    ("mrostdtextkey", "mrostdtextkey"),
    ("mrounitofmeasure", "mrounitofmeasure"),
    ("hashighpriorityalert", "hashighpriorityalert"),
]


COLS_REPLACED_FOR_STARTED_FIXED = [
    "timecreated",
    "timecreated_lcltz",
    "earlystart",
    "duedate",
    "timemodified",
    "jobstart",
    "jobfinish",
    "scheduleddate",
    "dispatchdate",
    "acknowledgeddate",
    "traveldate",
    "onsitedate",
    "completedate",
    "jobstartcal",
    "jobfinishcal",
    "traveldate_fixed",
    "onsitedate_fixed",
]

TIME_COLS_WITH_T = [
    ("assignmentstart", "jobstart"),
    ("assignmentfinish", "jobfinish"),
    ("dispatchdate", None),
    ("earlystart", None),
    ("duedate", None),
    ("timecreated", None),
    ("timemodified", None),
    ("acknowledgeddate", None),
    ("traveldate", None),
    ("onsitedate", None),
    ("canceldate", None),
    ("ondevicedate", None),
    ("completedate", None),
    ("scheduleddate", None),
]

DATE_COLUMNS_TO_EVAL_CASE_WHEN = [
    ("dispatchdate", None),
    ("acknowledgeddate", None),
    ("canceldate", None),
    ("scheduleddate", None),
    ("traveldate", None),
    ("onsitedate", None),
    ("traveldate", "traveldatedate"),
    ("onsitedate", "onsitedatedate"),
    ("completedate", None),
    ("ondevicedate", None),
    ("rejectdate", None),
]

ENGINEER_COLS = [
    "key",
    "revision",
    "region_key",
    "region_displaystring",
    "district_key",
    "district_displaystring",
    "name",
    "area_displaystring",
]

ASSET_COLS = [
    "key",
    "mrolocationtype_displaystring",
    "assetid",
    "mroassetfind",
    "mrosupfuncloc",
    "mrospeicalwellsproject",
    "shutinwell",
]

COLS_TO_DROP_TASK_REVISION_V2 = ["traveldatedate", "onsitedatedate", "jobstartdate", "jobfinishdate", "travelstart_tmp"]

TABLES_SCHEMA_R = [
    "task_keys_per_property",
    "task_last_revision_analytics",
    "assignment_by_engineer_date",
    "calendar_resource_intervals",
    "calendar_resource_intervals_history",
    "calendar_resource_intervals_history_by_calendar",
    "calendar_intervals_history_by_version",
]
TABLES_SCHEMA_S = ["assignment_validation", "region", "incomplete_reason", "district", "task"]
TABLES_SCHEMA_P = ["view_task_type_last_revision", "view_engineer_last_revision", "view_asset_last_revision"]
TABLES_BY_SCHEMA = {"r": TABLES_SCHEMA_R, "p": TABLES_SCHEMA_P, "s": TABLES_SCHEMA_S}

CAL_RESOURCES_HISTORY_COLS = [
    "resource_key",
    "resource_district_key",
    "interval_start",
    "interval_finish",
    "interval_status",
]
CAL_RESOURCES_HISTORY_BY_CALENDAR_COLS = [
    "calendar_key",
    "calendar_revision",
    "resource_key",
    "resource_district_key",
    "interval_start",
    "interval_finish",
    "interval_status",
]

CALENDAR_RESOURCES_COLUMNS = [
    "resource_key",
    "resource_district_key",
    "intervals",
    "calendar_key",
    "calendar_revision",
    "load_date",
]

TASK_COLUMNS_TO_SPLIT = [
    "key",
    "revision",
    "callid",
    "requiredskills1_key_key",
    "requiredskills1_key_displaystring",
    "assets_key",
    "assets_displaystring",
    "attachments_key",
    "attachments_displaystring",
    "backreportings",
    "engineerrequirements",
    "mrofailuredatalist",
    "excludedengineers_key",
    "excludedengineers_displaystring",
    "fsmopsaddonwork_key",
    "fsmopsaddonwork_displaystring",
    "mrorouterequirements",
    "mroswdmv_key",
    "mroswdmv_displaystring",
    "partsused",
    "preferredengineers",
    "requiredengineers_key",
    "requiredengineers_displaystring",
    "requiredengineertools",
    "requiredparts",
    "requiredskills2",
    "returnphotoskeys",
    "skillsduration_skill_key",
    "skillsduration_skill_displaystring",
    "subtasks_key",
    "subtasks_displaystring",
    "timedependencies",
    "usedpartsinstock",
]
